accounts/urls.py
from django.urls import path
from .views import login_view, register_view, logout_view

app_name = "accounts"

urlpatterns = [
    path("login/", login_view, name="login"),
    path("register/", register_view, name="register"),
    path("logout/", logout_view, name="logout"),
]

task/urls.py
from django.urls import path
from .views import TaskCreateView

app_name = "task"

urlpatterns = [path("create/", TaskCreateView.as_view(), name="create")]

task_creator/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic.base import RedirectView

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", RedirectView.as_view(pattern_name="task:create", permanent=False)),
    path("accounts/", include("accounts.urls", namespace="accounts")),
    path("task/", include("task.urls", namespace="task")),
]

accounts/models.py
from django.db import models

# Create your models here.

task/models.py
from django.db import models
from django.conf import settings
from django.db.models.signals import post_save
from django.dispatch import receiver
from django.core.mail import send_mail
from task_creator.utils import get_dot_env

# Create your models here.
class Task(models.Model):
    """Tasks Model"""

    title = models.CharField(max_length=50)
    description = models.TextField()
    due_date = models.DateField()
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)


@receiver(post_save, sender=Task)
def task_post_save(sender, instance, **kwargs):
    """Send mail to task.user with task detials post save"""
    send_mail(
        subject=instance.title,
        message=f"""
    description: {instance.description}
    due date: {instance.due_date}
    """,
        from_email=settings.FROM_EMAIL,
        recipient_list=[instance.user.email],
        fail_silently=True,
    )

accounts/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth import authenticate


class LoginForm(forms.Form):
    email = forms.EmailField()
    password = forms.CharField(widget=forms.PasswordInput())

    def clean(self):
        """
        Check if user exist and then authenticate password"""

        email = self.cleaned_data.get("email")
        password = self.cleaned_data.get("password")
        if not email or not password:
            return super().clean()
        user = User.objects.filter(email=email).first()
        if not user:
            raise forms.ValidationError("wrong email")
        self.user = authenticate(username=user.username, password=password)
        if self.user is None:
            raise forms.ValidationError("wrong email or password")
        return super().clean()


class RegisterForm(forms.ModelForm):
    first_name = forms.CharField()
    last_name = forms.CharField()
    password = forms.CharField(widget=forms.PasswordInput())

    class Meta:
        model = User
        fields = ("first_name", "last_name", "email", "password")

    def save(self, commit=True):
        """
        add username and password before saving user
        """
        user = super().save(commit=False)
        if commit:
            username = f"{user.first_name}_{user.last_name}"
            count = User.objects.filter(username=username).count()
            if count > 0:
                username = username + "_" + str(count + 1)
            user.username = username
            user.set_password(user.password)
            user.save()
        return user

    def clean_email(self):
        """Check if user already registered"""

        email = self.cleaned_data.get("email")
        if not email:
            return email
        user_qs = User.objects.filter(email=email)
        if user_qs:
            raise forms.ValidationError("email already exist")
        return email

task/forms.py
from django import forms
from .models import Task


class TaskForm(forms.ModelForm):
    due_date = forms.DateField(widget=forms.widgets.DateInput(attrs={"type": "date"}))

    def __init__(self, *args, **kwargs):
        self.request = kwargs.pop("request")
        super().__init__(*args, **kwargs)

    class Meta:
        model = Task
        exclude = ("user",)

    def save(self, commit=True):
        """add user to task instance"""

        task = super().save(commit=False)
        task.user = self.request.user
        if commit:
            task.save()
        return task

accounts/views.py
from django.shortcuts import render
from django.shortcuts import redirect
from django.contrib.auth import logout, login
from .forms import LoginForm, RegisterForm


def login_view(request):
    """View for logging users in"""

    if request.user.is_authenticated:
        return redirect("task:create")
    if request.method == "POST":
        form = LoginForm(request.POST)
        if form.is_valid():
            login(request, form.user)
            return redirect("task:create")
    else:
        form = LoginForm()

    return render(request, "accounts/login.html", {"form": form})


def register_view(request):
    """View for registering users"""

    if request.user.is_authenticated:
        return redirect("task:create")

    if request.method == "POST":
        form = RegisterForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect("accounts:login")
    else:
        form = RegisterForm()

    return render(request, "accounts/register.html", {"form": form})


def logout_view(request):
    """View for user logout"""
    logout(request)
    return redirect("accounts:login")

task/views.py
from django.views.generic import CreateView
from .models import Task
from .forms import TaskForm
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy


class TaskCreateView(LoginRequiredMixin, CreateView):
    """Create Task"""

    template_name = "task/create.html"
    form_class = TaskForm

    def get_form_kwargs(self):
        """Add request to form kwargs"""

        kwargs = super().get_form_kwargs()
        kwargs["request"] = self.request
        return kwargs

    def form_valid(self, form):
        """render same view with success message instead of redirect to success url"""

        self.object = form.save()
        context = self.get_context_data(form=self.form_class(request=self.request))
        context["msg"] = "An email with task details will be sent shortly"
        return self.render_to_response(context)

accounts/templates/accounts/login.html
{%extends 'base.html' %}

{% block body %}
<div class="row">
    <h1>Login</h1>
</div>


<form action="." method="post">
    {% include 'form.html' with form=form%}
    <div class="form-group col-4 offset-4">
        <button type="submit" class="btn btn-primary">Submit</button>
    </div>
</form>

{%endblock%}

accounts/templates/accounts/register.html
{%extends 'base.html' %}

{% block body %}
<div class="row">
    <h1>Register</h1>
</div>


<form action="." method="post">
    {% include 'form.html' with form=form%}
    <div class="form-group col-4 offset-4">
        <button type="submit" class="btn btn-primary">Submit</button>
    </div>

</form>

{%endblock%}

task/templates/task/create.html
{%extends 'base.html' %}

{% block body %}
<div class="row">
    <h1>Create Task</h1>
   
</div>


<form action="." method="post">
    {% include 'form.html' with form=form%}
    <div class="form-group col-4 offset-4">
        <button type="submit" class="btn btn-primary">Create</button>
    </div>

</form>

<div>
    {% if msg %}
        <h4 class="alert alert-success col-4 offset-4">{{msg}}</h4>
    {%endif%}
</div>

{%endblock%}

templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Task Creator</title>

    <!-- Custom fonts for this template-->
    <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" rel="stylesheet"
        type="text/css">

    <style>
        .errorlist {
            color: red
        }
        
        .top-nav {
            list-style-type: none;
            margin: 0;
            padding: 0;
            overflow: hidden;
            background-color: #333;
        }

        .top-nav li a {
            display: block;
            color: white;
            text-align: center;
            padding: 14px 16px;
            text-decoration: none;
        }

        .top-nav li a:hover {
            background-color: #111;
        }
    </style>
</head>

<body>
    <ul class="top-nav">
        {%if request.user.is_authenticated %}
        <li style="float: right;"><a href="{% url 'accounts:logout' %}">Logout</a></li>
        {%else%}
        <li style="float: left;"><a href="{% url 'accounts:register' %}">Register</a></li>
        <li style="float: left;"><a href="{% url 'accounts:login' %}">Login</a></li>
        {%endif%}
    </ul>

    <div class="container">
        {%block body%}
        {%endblock%}
    </div>
</body>


<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>

</body>

</html>

templates/form.html
{% load custom_tags %}


{% csrf_token %}
<div class="col-4 offset-4">
{{ form.non_field_errors }}
</div>

{% for field in form %}
<div class="form-group col-4 offset-4">
    {{ field.label_tag }} {{ field |add_class:"form-control"}}
    {{ field.errors }}

</div>
{% endfor %}